config/routes.rb
Rails.application.routes.draw do
  get 'transactions/new'
  get 'transactions/edit'
  resources :transactions
  get 'customers/new'
  get 'customers/edit'
  resources :customers
    get 'clients/new'
    get 'clients/edit'
    resources :clients

   root 'customers#index'

end

app/models/client.rb
class Client < ApplicationRecord
    has_many :transactions
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  skip_before_action :verify_authenticity_token

  def index
    @clients = Client.select(:id,:name).all
  end

  def show
    @client = Client.find(params[:id])
  end

  def new
    @client = Client.new
  end

  def edit
    @client = Client.find(params[:id])
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      flash[:notice] = 'Client added!'
      redirect_to clients_path
    else
      flash[:error] = 'Failed to edit Client!'
      render :new
    end
  end

  def update
      @client = Client.find(params[:id])
      if @client.update_attributes(client_params)
        flash[:notice] = 'Client updated!'
        redirect_to clients_path
      else
        flash[:error] = 'Failed to edit Client!'
        render :edit
      end
  end

  def destroy
      @client = Client.find(params[:id])
      if @client.delete
        flash[:notice] = 'Client deleted!'
        redirect_to clients_path
      else
        flash[:error] = 'Failed to delete this Client!'
        render :destroy
      end
  end

  def client_params
      params.require(:client).permit(:name)
  end
end

app/views/clients/edit.html.erb
<div class="container">

<%= form_for @client, url: {action: :update} do |f| %>
<%= csrf_meta_tags %>

   <h3>Edit Client</h3>
 <%= "<div>#{@client.errors.full_messages.first}</div>".html_safe if @client.errors.any? %>
    <p>

     <div>
            <label>Client Name</label>
            <%= f.text_field :name %>
     </div>

      </p>
   <div>
      <%= link_to 'Back', { controller: 'clients', action: 'index'} %>
      <%= f.submit 'Update Client' %>
    </div>
<% end %>
</div>

app/views/clients/index.html.erb
<!DOCTYPE html>
<html>
<body>
 <div class="container">
    <%= flash[:notice] %>
    <h3>Client List</h3>

      <div>
        <%= link_to 'Add Client', clients_new_path %>
      </div>
      <br>
    <table border="2">
      <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @clients.each do |client| %>
          <tr>
            <td><%= client.id %></td>
            <td><%= client.name %></td>

           <div>
               <td>
                <%= link_to 'Edit', edit_client_path(client) %>
                <%= link_to 'Delete', client_path(client), method: :delete, data: { confirm: 'Are you sure?' } %>
           </div>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
    </div>
  </body>
</html>

app/views/clients/new.html.erb
<div class="container">
  <%= form_for @client, url: {action: :create} do |f| %>
  <%= csrf_meta_tags %>
      <div>
        <h3>Add a Client</h3>
      </div>
      <div>
        <p>
          <%= "<div>#{@client.errors.full_messages.first}</div>".html_safe if @client.errors.any? %>
        <div>
            <label>Client Name</label>
              <%= f.text_field :name %>
        </div>
      <div>
        <%= link_to 'Back', { controller: 'clients', action: 'index'} %>
        <%= f.submit 'Create Client' %>
      </div>
  <% end %>
</div>