config/routes.rb
Rails.application.routes.draw do
  get 'transactions/new'
  get 'transactions/edit'
  resources :transactions
  get 'customers/new'
  get 'customers/edit'
  resources :customers
    get 'clients/new'
    get 'clients/edit'
    resources :clients

   root 'customers#index'

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  skip_before_action :verify_authenticity_token
  def index
    @transactions = Transaction.all
  end

  def show
    @transaction = Transaction.find(params[:id])
  end

  def new
    @transaction = Transaction.new
  end

  def create
    @transaction = Transaction.new(transaction_params)
    if @transaction.save
      flash[:notice] = 'Transaction added!'
      redirect_to transactions_path
    else
      flash[:error] = 'Failed to edit Transaction!'
      render :new
    end
  end

  def edit
    @transaction = Transaction.find(params[:id])
  end

  def update
    @transaction = Transaction.find(params[:id])
    if @transaction.update_attributes(transaction_params)
      flash[:notice] = 'Transaction updated!'
      redirect_to transactions_path
    else
      flash[:error] = 'Failed to edit Transaction!'
      render :edit
    end
  end

  def destroy
    @transaction = Transaction.find(params[:id])
    if @transaction.delete
      flash[:notice] = 'Transaction deleted!'
      redirect_to transactions_path
    else
      flash[:error] = 'Failed to delete this Transaction!'
      render :destroy
    end
  end

  def transaction_params
     params.require(:transaction).permit(:client_id, :customer_id, :amount, :currency_code, :transaction_date)
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/edit.html.erb
<h1>Transactions#edit</h1>
<p>Find me in app/views/transactions/edit.html.erb</p>

app/views/transactions/index.html.erb
<!DOCTYPE html>
<html>
<body>
 <div class="container">
    <div>
        <ul>
            <li><%= link_to 'Customers', customers_path %></li>
            <li><%= link_to 'Clients', clients_path %></li>
            <li><%= link_to 'Transactions', transactions_path %></li>
        </ul>
    </div>
    <%= flash[:notice] %>
    <h3>Transaction List</h3>

      <div>
        <%= link_to 'Add Transaction', transactions_new_path %>
      </div>
      <br>
    <table border="2">
      <thead>
      <tr>
        <th>ID</th>
        <th>Customer</th>
        <th>Client</th>
        <th>Amount</th>
        <th>Currency</th>
        <th>Transaction Date</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @transactions.each do |transaction| %>
          <tr>
            <td><%= transaction.id %></td>
            <td><%= transaction.customer.name %></td>
            <td><%= transaction.client.name %></td>
            <td><%= transaction.amount %></td>
            <td><%= transaction.currency_code %></td>
            <td><%= transaction.transaction_date.strftime("%d-%m-%Y") %></td>

           <div>
               <td>
                <%= link_to 'Delete', transaction_path(transaction), method: :delete, data: { confirm: 'Are you sure?' } %>

            </td>
            </div>
          </tr>
      <% end %>
      </tbody>
    </table>
    </div>
  </body>
</html>

app/views/transactions/new.html.erb
<div class="container">
  <%= form_for @transaction, url: {action: :create} do |f| %>
  <%= csrf_meta_tags %>
      <div>
        <h3>Add a Transaction</h3>
      </div>
      <div>
        <p>
          <%= "<div>#{@transaction.errors.full_messages.first}</div>".html_safe if @transaction.errors.any? %>
        <div>
            <label>Customer</label>
              <%= collection_select(:transaction, :customer_id, Customer.all, :id, :name) %>
        </div>
        <div>
            <label>Client</label>
              <%= collection_select(:transaction, :client_id, Client.all, :id, :name) %>
        </div>
        <div>
            <label>Amount</label>
             <%= f.number_field :amount, step: 0.5 %>
        </div>
        <div>
            <label>Currency Code</label>
            <%= f.select :currency_code, ['USD', 'EUR', 'INR', 'GBP']%>
        </div>
        <div>
            <label>Transaction Date</label>
              <%= f.date_field :transaction_date %>
        </div>
      <div>
        <%= link_to 'Back', { controller: 'transactions', action: 'index'} %>
        <%= f.submit 'Create Transaction' %>
      </div>
  <% end %>
</div>

app/views/transactions/show.html.erb
<h1>Transactions#show</h1>
<p>Find me in app/views/transactions/show.html.erb</p>